# Generated by Django 2.2.14 on 2020-11-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0002_auto_20201129_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Seller_SKU',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
