# Generated by Django 2.2.14 on 2020-11-29 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0003_item_seller_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_by_seller',
            name='MRP',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='item_by_seller',
            name='Pincode_pro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item_by_seller',
            name='Produt_tax_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item_by_seller',
            name='Seller_SKU',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item_by_seller',
            name='Shipping_Mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_home.SHIPPING_MODE'),
        ),
    ]
