# Generated by Django 2.2.14 on 2020-11-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0004_auto_20201129_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_by_seller',
            name='Brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
