# Generated by Django 2.2.14 on 2020-12-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0005_item_by_seller_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
