# Generated by Django 2.2.14 on 2020-12-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0007_auto_20201201_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_by_seller',
            name='MRP',
            field=models.FloatField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='item_by_seller',
            name='description_by_seller',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item_by_seller',
            name='image_by_seller',
            field=models.ImageField(null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='item_by_seller',
            name='price_by_seller',
            field=models.FloatField(null=True),
        ),
    ]
