# Generated by Django 2.2.14 on 2020-12-02 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0009_auto_20201202_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_by_seller',
            name='Shipping_Mode',
            field=models.ForeignKey(default='ALMORIANS', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_home.SHIPPING_MODE'),
        ),
    ]
