# Generated by Django 2.2.14 on 2020-12-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0011_orderitem_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
