# Generated by Django 2.2.14 on 2020-12-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0014_auto_20201205_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='address',
            name='default',
        ),
    ]
