# Generated by Django 2.2.14 on 2020-12-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0016_auto_20201208_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_received',
            field=models.BooleanField(default=False),
        ),
    ]
