# Generated by Django 2.2.14 on 2020-12-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0019_auto_20201209_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_dispached',
            field=models.BooleanField(default=False),
        ),
    ]
