# Generated by Django 2.2.14 on 2020-12-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0020_auto_20201209_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_dispached',
            new_name='order_dispatched',
        ),
    ]
