# Generated by Django 2.2.14 on 2020-12-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0022_auto_20201210_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
