# Generated by Django 2.2.14 on 2020-12-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0025_banner2'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Deals_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
