# Generated by Django 2.2.14 on 2020-12-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0026_item_deals_of_the_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='ViewType',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='numberOfBanners',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='banner2',
            name='ViewType',
            field=models.IntegerField(default=0),
        ),
    ]
