# Generated by Django 2.2.14 on 2020-12-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0027_auto_20201222_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bgColor',
            field=models.TextField(default='#FFFFFF'),
        ),
    ]
