# Generated by Django 2.2.14 on 2020-12-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0030_auto_20201222_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ViewType',
        ),
    ]
